[package]
name = "uniffi-bindgen"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "uniffi-bindgen"

[bindings.swift]
omit_checksums = true

[dependencies]
uniffi = { version = "0.29.2", features = ["cli"] }